version: '3'

services:
  webserver:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/laravel
    depends_on:
      - backend
    networks:
      - main

  backend:
    build: ./
    volumes:
      - ./:/var/www/html/laravel
    networks:
      - main

networks:
  main:
    driver: bridge
