version: '3'

services:
  webserver:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/html/laravel:cached
    depends_on:
      - backend
    networks:
      - main

  backend:
    build: .container/php
    volumes:
      - ./:/var/www/html/laravel:cached
    networks:
      - main

networks:
  main:
    driver: bridge
